# Generated by Django 2.2.2 on 2019-08-05 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('where_from', models.CharField(default='', max_length=10)),
                ('mark', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
