# Generated by Django 2.2.2 on 2019-08-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(default='', max_length=20)),
                ('ip_address', models.CharField(default='', max_length=20)),
                ('where_use', models.CharField(default='', max_length=20)),
                ('is_default', models.CharField(default='', max_length=20)),
                ('device_type', models.CharField(default='', max_length=20)),
                ('goodsType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_goods_type_id', to='models.GoodsType')),
            ],
        ),
    ]
