# Generated by Django 2.2.2 on 2019-08-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_desk_id', to='models.Desk'),
            preserve_default=False,
        ),
    ]
