# Generated by Django 2.2.2 on 2019-08-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_order_desk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
    ]
