# Generated by Django 2.2.2 on 2019-08-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_profit',
        ),
    ]
