# Generated by Django 2.2.2 on 2019-08-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_order_total_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='goodsType_Name',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='goodsType_id',
        ),
    ]
