# Generated by Django 2.2.2 on 2019-08-14 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190814_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bussnessDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
