# Generated by Django 2.2.2 on 2019-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20190814_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='printer_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
