# Generated by Django 2.2.2 on 2019-08-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20190814_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限标题')),
                ('url', models.CharField(max_length=128, verbose_name='资源的URL')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='URL别名')),
            ],
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='类型描述'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='name',
            field=models.CharField(max_length=10, verbose_name='商品类型名称'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='device_type',
            field=models.CharField(default='', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='goodsType_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_goods_type_id', to='models.GoodsType', verbose_name='商品分类编号'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(default='', max_length=20, verbose_name='打印机IP地址'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='is_default',
            field=models.CharField(default='', max_length=20, verbose_name='是否默认打印机'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_name',
            field=models.CharField(default='', max_length=50, verbose_name='打印机名称'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='where_use',
            field=models.CharField(default='', max_length=20, verbose_name='使用地方'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='所在地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(auto_now_add=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='', upload_to='img', verbose_name='用户头像的URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(default='', max_length=100, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='手机号码'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(blank=True, to='models.Permission', verbose_name='拥有的所有权限')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='models.Role', verbose_name='拥有的所有的角色'),
        ),
    ]
