# Generated by Django 2.2.2 on 2019-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='goods_name',
            field=models.CharField(max_length=20),
        ),
    ]
