# Generated by Django 2.2.2 on 2019-07-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190709_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_goods_id', to='goods.Goods', unique=True),
        ),
    ]
