# Generated by Django 2.2.2 on 2019-07-07 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(default='', max_length=2)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('goodsType_Name', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(default='', upload_to='img')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goodsType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_goods_type_id', to='sale.GoodsType')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_mer_id', to='merchant.Merchant')),
            ],
        ),
    ]
