# Generated by Django 2.2.2 on 2019-08-05 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=2)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('goodsType_Name', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(default='', upload_to='img')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_pice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
