# Generated by Django 2.2.2 on 2019-08-06 16:10

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190805_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='merchant_id',
        ),
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='img/%Y/%m/%d'),
        ),
    ]
