# Generated by Django 2.2.2 on 2019-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190709_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='wholesale_pice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
