# Generated by Django 2.2.2 on 2019-08-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190806_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='wholesale_pice',
        ),
    ]
