# Generated by Django 2.2.2 on 2019-07-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('merchant', '0001_initial'),
        ('sale', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goodsType_Name', models.CharField(default='', max_length=20)),
                ('goodsType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_goods_type_id', to='sale.GoodsType')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_goods_id', to='goods.Goods')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_mer_id', to='merchant.Merchant')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_id', to='order.Order')),
            ],
        ),
    ]
