# Generated by Django 2.2.2 on 2019-08-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('sale', '0001_initial'),
        ('goods', '0002_auto_20190805_1759'),
        ('orderdetail', '0001_initial'),
        ('order', '0002_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='goodsType_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_goods_type_id', to='sale.GoodsType'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_goods_id', to='goods.Goods'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_mer_id', to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_id', to='order.Order', to_field='order_code'),
        ),
    ]
