# Generated by Django 2.2.2 on 2019-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetail', '0002_auto_20190805_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='merchant_id',
        ),
    ]
