# Generated by Django 2.2.2 on 2019-07-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetail', '0002_auto_20190707_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_id', to='order.Order', to_field='order_code'),
        ),
    ]
