# Generated by Django 2.2.2 on 2019-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetail', '0003_auto_20190707_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_name',
            field=models.CharField(max_length=20),
        ),
    ]
