# Generated by Django 2.2.2 on 2019-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190714_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goods_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
