# Generated by Django 2.2.2 on 2019-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
