# Generated by Django 2.2.2 on 2019-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
