# Generated by Django 2.2.2 on 2019-06-22 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 11, 10, 23, 227342, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='role_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='create_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
