# Generated by Django 2.2.2 on 2019-06-22 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190622_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
