# Generated by Django 2.2.2 on 2019-06-22 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190622_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('where_from', models.CharField(default='', max_length=10)),
                ('mark', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=10)),
                ('customer_id', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='', max_length=500)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_method', models.CharField(max_length=10)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='desc',
            new_name='description',
        ),
    ]
