# Generated by Django 2.2.2 on 2019-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190710_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1992-08-16'),
        ),
    ]
