# Generated by Django 2.2.2 on 2019-06-22 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20190622_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(default='', max_length=2)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('goodsType_Name', models.CharField(default='', max_length=20)),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(default='', max_length=500)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('where_from', models.CharField(default='', max_length=10)),
                ('mark', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=5)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.CharField(default='', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goodsType_Name', models.CharField(default='', max_length=20)),
                ('goodsType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_goods_type_id', to='sale.GoodsType')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_goods_id', to='sale.Goods')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_mer_id', to='sale.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_goods_id', to='sale.Goods')),
            ],
        ),
        migrations.DeleteModel(
            name='PayInfo',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='role',
            name='user_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='create_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_id', to='sale.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsType_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_goods_type_id', to='sale.GoodsType'),
        ),
        migrations.AddField(
            model_name='goods',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_mer_id', to='sale.Merchant'),
        ),
    ]
