# Generated by Django 2.2.2 on 2019-06-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20190622_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='regist_time',
            new_name='sign_up_time',
        ),
    ]
