# Generated by Django 2.2.2 on 2019-07-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20190710_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
