# Generated by Django 2.2.2 on 2019-06-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20190623_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
