# Generated by Django 2.2.2 on 2019-08-05 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(default='', max_length=10)),
                ('num', models.IntegerField(default=0)),
                ('goods_name', models.CharField(default='', max_length=100)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_goods_id', to='goods.Goods')),
            ],
        ),
    ]
