# Generated by Django 2.2.2 on 2019-07-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=5)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bussnessDate', models.DateField(default=django.utils.timezone.now)),
                ('mark', models.CharField(default='', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.CharField(default='', max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='customer.Customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
