# Generated by Django 2.2.2 on 2019-07-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190707_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
